---
- hosts: webservers
  become: true
  vars_files:
    - vars/default.yaml

  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest

    - name: enable mod_rewrite
      apache2_module: name=rewrite state=present
      notify: restart apache2

    - name: Create document root
      file: 
        path: /var/www/{{ http_host }}
        state: directory
        owner: "www-data"
        group: "www-data"
        mode: "0755"

    - name: Set up Apache virtualhost
      template: 
        src: "files/apache.conf.j2"
        dest: "/etc/apache2/sites-available/{{ http_conf }}"
      notify: reload apache2

    - name: Enable new site
      shell: /usr/sbin/a2ensite {{ http_conf }}
      notify: reload apache2

    - name: Disable default Apache site
      shell: /usr/sbin/a2dissite 000-default.conf
      when: disable_default
      notify: reload apache2

  handlers:
    - name: restart apache2
      service: 
        name: apache2 
        state: restarted

    - name: reload apache2
      service:
        name: apache2
        state: reloaded

